"""
Project API routes.
"""

import logging
from typing import List, Optional
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File, Form
from sqlalchemy.orm import Session
from backend.core.database import get_db
from backend.services.project_service import ProjectService
from backend.services.processing_service import ProcessingService
from backend.services.websocket_notification_service import WebSocketNotificationService
# Lazily imported to avoid triggering the celery_app import chain early
# from backend.tasks.processing import process_video_pipeline
from backend.core.websocket_manager import manager as websocket_manager
from backend.schemas.project import (
    ProjectCreate, ProjectUpdate, ProjectResponse, ProjectListResponse, ProjectFilter,
    ProjectType, ProjectStatus
)
from backend.schemas.base import PaginationParams
from pathlib import Path

logger = logging.getLogger(__name__)
router = APIRouter()


def get_project_service(db: Session = Depends(get_db)) -> ProjectService:
    """Dependency to get project service."""
    return ProjectService(db)


def get_processing_service(db: Session = Depends(get_db)) -> ProcessingService:
    """Dependency to get processing service."""
    return ProcessingService(db)


def get_websocket_service():
    """Dependency to get websocket notification service."""
    return WebSocketNotificationService


@router.post("/upload", response_model=ProjectResponse)
async def upload_files(
    video_file: UploadFile = File(...),
    srt_file: Optional[UploadFile] = File(None),
    project_name: str = Form(...),
    video_category: Optional[str] = Form(None),
    project_service: ProjectService = Depends(get_project_service)
):
    """Upload video file and optional subtitle file to create a new project. If no subtitle is provided, Whisper will automatically generate one."""
    try:
        # Validate the video file type
        if not video_file.filename.lower().endswith(('.mp4', '.avi', '.mov', '.mkv', '.webm')):
            raise HTTPException(status_code=400, detail="Invalid video file format")

        # Validate the subtitle file type (when provided)
        if srt_file and not srt_file.filename.lower().endswith('.srt'):
            raise HTTPException(status_code=400, detail="Invalid subtitle file format")

        # Build the project data
        subtitle_info = srt_file.filename if srt_file else "Auto-generated by Whisper"
        project_data = ProjectCreate(
            name=project_name,
            description=f"Video: {video_file.filename}, Subtitle: {subtitle_info}",
            project_type=ProjectType.KNOWLEDGE,  # default type
            status=ProjectStatus.PENDING,
            source_url=None,
            source_file=video_file.filename,
            settings={
                "video_category": video_category or "knowledge",
                "video_file": video_file.filename,
                "srt_file": subtitle_info
            }
        )

        # Create the project
        project = project_service.create_project(project_data)

        # Save files into the project directory
        project_id = str(project.id)
        from ...core.path_utils import get_project_raw_directory
        raw_dir = get_project_raw_directory(project_id)

        # Save the video file
        video_path = raw_dir / "input.mp4"
        with open(video_path, "wb") as f:
            content = await video_file.read()
            f.write(content)

        # Update the project's video path
        project.video_path = str(video_path)
        project_service.db.commit()

        # Generate the thumbnail immediately (synchronously)
        try:
            from ...utils.thumbnail_generator import generate_project_thumbnail
            logger.info(f"Generating thumbnail for project {project_id}...")
            thumbnail_data = generate_project_thumbnail(project_id, video_path)
            if thumbnail_data:
                project.thumbnail = thumbnail_data
                project_service.db.commit()
                logger.info(f"Project {project_id} thumbnail generated and saved")
            else:
                logger.warning(f"Project {project_id} thumbnail generation failed")
        except Exception as e:
            logger.error(f"Error generating project thumbnail: {e}")
            # Thumbnail failures don't block the main flow; retried in the async task

        # Handle the subtitle file (when the user provided one)
        srt_path = None
        if srt_file:
            # User-provided subtitles
            srt_path = raw_dir / "input.srt"
            with open(srt_path, "wb") as f:
                content = await srt_file.read()
                f.write(content)
            logger.info(f"User-provided subtitle file saved: {srt_path}")

        # Start the async processing task
        try:
            from ...tasks.import_processing import process_import_task

            # Skip when the same project is already processing
            from ...models.task import Task, TaskStatus
            # This used to reference a bare `db` (undefined); the NameError was swallowed by the except below,
            # so locally uploaded projects never started processing and stayed pending until clicked manually
            existing_task = project_service.db.query(Task).filter(
                Task.project_id == project_id,
                Task.status == TaskStatus.RUNNING,
                Task.name.like('%import%')
            ).first()

            if existing_task:
                logger.warning(f"Project {project_id} already has a running task; skipping duplicate start")
            else:
                # Submit the async task
                celery_task = process_import_task.delay(
                    project_id=project_id,
                    video_path=str(video_path),
                    srt_file_path=str(srt_path) if srt_path else None
                )

                logger.info(f"Project {project_id} async task started, Celery task ID: {celery_task.id}")

        except Exception as e:
            logger.error(f"Failed to start async processing for project {project_id}: {str(e)}")
            # Even when the async task fails to start, report the project as created
            # Users can restart processing via the retry button

        # Build the project response
        response_data = {
            "id": str(project.id),
            "name": str(project.name),
            "description": str(project.description) if project.description else None,
            "project_type": ProjectType(project.project_type.value),
            "status": ProjectStatus(project.status.value),
            "source_url": project.project_metadata.get("source_url") if project.project_metadata else None,
            "source_file": str(project.video_path) if project.video_path else None,
            "video_path": str(video_path),  # video_path field
            "settings": {
                "video_category": video_category or "knowledge",
                "video_file": video_file.filename,
                "srt_file": subtitle_info
            },  # serializable data only
            "created_at": project.created_at,
            "updated_at": project.updated_at,
            "completed_at": project.completed_at,
            "total_clips": 0,
            "total_collections": 0,
            "total_tasks": 0
        }

        # Thumbnail is generated in the async task
        response_data["thumbnail"] = None

        return ProjectResponse(**response_data)

    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to create project from uploaded files")
        raise HTTPException(status_code=500, detail="Failed to create project; please try again later")


@router.post("/", response_model=ProjectResponse)
async def create_project(
    project_data: ProjectCreate,
    project_service: ProjectService = Depends(get_project_service)
):
    """Create a new project."""
    try:
        project = project_service.create_project(project_data)
        # Convert to response (simplified for now)
        return ProjectResponse(
            id=str(project.id),  # Use actual project ID
            name=str(project.name),
            description=str(project.description) if project.description else None,
            project_type=ProjectType(project.project_type.value),
            status=ProjectStatus(project.status.value),
            source_url=project.project_metadata.get("source_url") if project.project_metadata else None,
            source_file=str(project.video_path) if project.video_path else None,
            settings=project.processing_config or {},
            created_at=project.created_at,
            updated_at=project.updated_at,
            completed_at=project.completed_at,
            total_clips=0,
            total_collections=0,
            total_tasks=0
        )
    except Exception as e:
        logger.exception("Failed to create project")
        raise HTTPException(status_code=500, detail="Failed to create project; please try again later")


@router.get("/", response_model=ProjectListResponse)
async def get_projects(
    page: int = Query(1, ge=1, description="Page number"),
    size: int = Query(20, ge=1, le=100, description="Page size"),
    status: Optional[str] = Query(None, description="Filter by status"),
    project_type: Optional[str] = Query(None, description="Filter by project type"),
    search: Optional[str] = Query(None, description="Search in name and description"),
    project_service: ProjectService = Depends(get_project_service)
):
    """Get paginated projects with optional filtering."""
    try:
        pagination = PaginationParams(page=page, size=size)

        filters = None
        if status or project_type or search:
            # Convert strings to enums
            status_enum = None
            if status:
                try:
                    status_enum = ProjectStatus(status)
                except ValueError:
                    raise HTTPException(status_code=400, detail=f"Invalid status: {status}")

            project_type_enum = None
            if project_type:
                try:
                    project_type_enum = ProjectType(project_type)
                except ValueError:
                    raise HTTPException(status_code=400, detail=f"Invalid project_type: {project_type}")

            filters = ProjectFilter(
                status=status_enum,
                project_type=project_type_enum,
                search=search
            )

        return project_service.get_projects_paginated(pagination, filters)
    except Exception as e:
        logger.exception("Failed to get project list")
        raise HTTPException(status_code=500, detail="Failed to get project list; please try again later")


@router.get("/{project_id}", response_model=ProjectResponse)
async def get_project(
    project_id: str,
    include_clips: bool = Query(False, description="Whether to include clip data"),
    include_collections: bool = Query(False, description="Whether to include collection data"),
    project_service: ProjectService = Depends(get_project_service)
):
    """Get a project by ID."""
    try:
        project = project_service.get_project_with_stats(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Load clips/collections data when requested
        clips_data = None
        collections_data = None

        if include_clips or include_collections:
            from ...services.clip_service import ClipService
            from ...services.collection_service import CollectionService
            from ...core.database import get_db

            # Get a DB session
            db = next(get_db())

            if include_clips:
                clip_service = ClipService(db)
                clips = clip_service.get_multi(filters={"project_id": project_id})
                # Convert to dicts
                clips_data = [clip.to_dict() if hasattr(clip, 'to_dict') else clip.__dict__ for clip in clips]

            if include_collections:
                collection_service = CollectionService(db)
                collections = collection_service.get_multi(filters={"project_id": project_id})
                # Convert to dicts
                collections_data = [collection.to_dict() if hasattr(collection, 'to_dict') else collection.__dict__ for collection in collections]

        # Build the response including clips/collections
        response_data = project.model_dump() if hasattr(project, 'model_dump') else project.__dict__
        if clips_data is not None:
            response_data['clips'] = clips_data
        if collections_data is not None:
            response_data['collections'] = collections_data

        # Return the updated response
        return ProjectResponse(**response_data)
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to get project details: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to get project details; please try again later")


@router.put("/{project_id}", response_model=ProjectResponse)
async def update_project(
    project_id: str,
    project_data: ProjectUpdate,
    project_service: ProjectService = Depends(get_project_service)
):
    """Update a project."""
    try:
        project = project_service.update_project(project_id, project_data)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")
        
        # Convert to response (simplified)
        return ProjectResponse(
            id=str(project_id),  # Keep as string for UUID
            name=project_data.name or "Updated Project",
            description=project_data.description,
            project_type=ProjectType.DEFAULT,  # Use enum
            status=ProjectStatus.PENDING,  # Use enum
            source_url=None,
            source_file=None,
            settings=project_data.settings or {},
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
            completed_at=None,
            total_clips=0,
            total_collections=0,
            total_tasks=0
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to update project: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to update project; please try again later")


@router.delete("/{project_id}")
async def delete_project(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service)
):
    """Delete a project and all its related files."""
    try:
        success = project_service.delete_project_with_files(project_id)
        if not success:
            raise HTTPException(status_code=404, detail="Project not found")
        return {"message": "Project and all related files deleted successfully"}
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to delete project: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to delete project; please try again later")


@router.post("/sync-all-data")
async def sync_all_projects_data(
    db: Session = Depends(get_db)
):
    """Sync all projects' data to the database"""
    try:
        from ...services.data_sync_service import DataSyncService
        from ...core.config import get_data_directory

        data_dir = get_data_directory()
        sync_service = DataSyncService(db)

        result = sync_service.sync_all_projects_from_filesystem(data_dir)

        return {
            "message": "Data sync completed",
            "result": result
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Data sync failed: {str(e)}")


@router.post("/{project_id}/sync-data")
async def sync_project_data(
    project_id: str,
    db: Session = Depends(get_db)
):
    """Sync one project's data to the database"""
    try:
        from ...services.data_sync_service import DataSyncService
        from ...core.path_utils import get_project_directory

        project_dir = get_project_directory(project_id)
        if not project_dir.exists():
            raise HTTPException(status_code=404, detail="Project directory not found")

        sync_service = DataSyncService(db)
        result = sync_service.sync_project_from_filesystem(project_id, project_dir)

        if result.get("success"):
            return {
                "message": "Project data synced",
                "result": result
            }
        else:
            raise HTTPException(status_code=500, detail=f"Data sync failed: {result.get('error')}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Data sync failed: {str(e)}")


@router.post("/{project_id}/process")
async def start_processing(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service),
    processing_service: ProcessingService = Depends(get_processing_service),
    websocket_service: WebSocketNotificationService = Depends(get_websocket_service)
):
    """Start processing a project using Celery task queue."""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Check the project status
        if project.status.value not in ["pending", "failed"]:
            raise HTTPException(status_code=400, detail="Project is not in pending or failed status")

        # Get video and SRT paths
        video_path = project.video_path
        srt_path = None

        # Get the SRT path from the processing config
        if project.processing_config and "subtitle_path" in project.processing_config:
            srt_path = project.processing_config["subtitle_path"]

        # Verify the video file exists
        if not video_path or not Path(video_path).exists():
            raise HTTPException(status_code=400, detail=f"Video file not found: {video_path}")

        # Auto-locate the SRT file when no path is set
        if not srt_path:
            video_dir = Path(video_path).parent
            srt_file = video_dir / "input.srt"
            if srt_file.exists():
                srt_path = str(srt_file)
            else:
                # SRT is optional; leave empty when not found
                srt_path = None
        elif not Path(srt_path).exists():
            # Auto-locate when the configured SRT file is missing
            video_dir = Path(video_path).parent
            srt_file = video_dir / "input.srt"
            if srt_file.exists():
                srt_path = str(srt_file)
            else:
                srt_path = None

        # Mark the project as processing
        project_service.update_project_status(project_id, "processing")

        # WebSocket notification: processing started
        await websocket_service.send_processing_started(
            project_id=project_id,
            message="Video processing started"
        )

        # Lazily imported to avoid triggering the celery_app import chain early
        from backend.tasks.processing import process_video_pipeline

        # Submit the Celery task
        celery_task = process_video_pipeline.delay(
            project_id=project_id,
            input_video_path=str(video_path),
            input_srt_path=str(srt_path) if srt_path else None
        )

        # Create the processing task record
        task_result = processing_service._create_processing_task(
            project_id=project_id,
            task_type="VIDEO_PROCESSING"
        )
        
        return {
            "message": "Processing started successfully",
            "project_id": project_id,
            "task_id": task_result.id,
            "celery_task_id": celery_task.id,
            "status": "processing"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        # Send the error notification
        try:
            await websocket_service.send_processing_error(
                project_id=int(project_id),
                error=str(e),
                step="initialization"
            )
        except:
            pass
        logger.exception("Failed to start project processing: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to start processing; please try again later")


@router.post("/{project_id}/retry")
async def retry_processing(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service),
    processing_service: ProcessingService = Depends(get_processing_service),
    websocket_service: WebSocketNotificationService = Depends(get_websocket_service)
):
    """Retry processing a project from the beginning."""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Check the project status - failed, completed, processing, and pending can retry
        if project.status.value not in ["failed", "completed", "processing", "pending"]:
            raise HTTPException(status_code=400, detail="Project is not in failed, completed, processing, or pending status")

        # Reset the project status
        project_service.update_project_status(project_id, "pending")

        # WebSocket notification - disabled
        # await websocket_service.send_processing_started(
        #     project_id=int(project_id),
        #     message="Restarting the processing pipeline"
        # )

        # Resolve file paths and resubmit the task
        from ...core.path_utils import get_project_raw_directory
        raw_dir = get_project_raw_directory(project_id)
        video_path = raw_dir / "input.mp4"  # standard input.mp4 name
        srt_path = raw_dir / "input.srt"    # standard input.srt name

        # Re-download when the video file is missing
        if not video_path.exists():
            logger.warning(f"Video file missing: {video_path}; attempting re-download")

            # Check the project metadata for a source URL
            if hasattr(project, 'project_metadata') and project.project_metadata:
                source_url = project.project_metadata.get('source_url')
                if source_url:
                    logger.info(f"Found source URL: {source_url}; re-downloading")

                    # Pick the downloader by URL type
                    if 'bilibili.com' in source_url:
                        # Re-download the Bilibili video
                        from .bilibili import process_download_task, BilibiliDownloadRequest, BilibiliDownloadTask, download_tasks
                        import uuid

                        # Build the download request
                        download_request = BilibiliDownloadRequest(
                            url=source_url,
                            project_name=project.name,
                            video_category=project.project_metadata.get('category', 'general')
                        )

                        # Generate a new task ID
                        download_task_id = str(uuid.uuid4())

                        # Create the task record
                        task = BilibiliDownloadTask(
                            id=download_task_id,
                            url=source_url,
                            project_name=project.name,
                            video_category=project.project_metadata.get('category', 'general'),
                            status="pending",
                            progress=0.0,
                            project_id=project_id,
                            created_at=str(uuid.uuid1().time),
                            updated_at=str(uuid.uuid1().time)
                        )

                        # Store the task
                        download_tasks[download_task_id] = task

                        # Start the download task asynchronously
                        from .async_task_manager import task_manager
                        await task_manager.create_safe_task(
                            f"bilibili_redownload_{download_task_id}",
                            process_download_task,
                            download_task_id,
                            download_request,
                            project_id
                        )

                        return {
                            "message": "Video file missing; re-download of the Bilibili video started",
                            "project_id": project_id,
                            "download_task_id": download_task_id,
                            "source_url": source_url
                        }
                    elif 'youtube.com' in source_url or 'youtu.be' in source_url:
                        # Re-download the YouTube video
                        from .youtube import process_youtube_download_task, YouTubeDownloadRequest
                        import uuid

                        # Build the download request
                        download_request = YouTubeDownloadRequest(
                            url=source_url,
                            project_name=project.name,
                            video_category=project.project_metadata.get('category', 'general')
                        )

                        # Generate a new task ID
                        download_task_id = str(uuid.uuid4())

                        # Start the download task asynchronously
                        from .async_task_manager import task_manager
                        await task_manager.create_safe_task(
                            f"youtube_redownload_{download_task_id}",
                            process_youtube_download_task,
                            download_task_id,
                            download_request,
                            project_id
                        )

                        return {
                            "message": "Video file missing; re-download of the YouTube video started",
                            "project_id": project_id,
                            "download_task_id": download_task_id,
                            "source_url": source_url
                        }
                    else:
                        raise HTTPException(status_code=400, detail=f"Unsupported video source: {source_url}")
                else:
                    raise HTTPException(status_code=400, detail=f"Video file missing with no source URL: {video_path}")
            else:
                raise HTTPException(status_code=400, detail=f"Video file missing with no project metadata: {video_path}")

        # Subtitles are optional
        srt_path_str = str(srt_path) if srt_path.exists() else None

        # Lazily imported to avoid triggering the celery_app import chain early
        from backend.tasks.processing import process_video_pipeline

        # Submit the Celery task - project_id as string
        celery_task = process_video_pipeline.delay(
            project_id=project_id,
            input_video_path=str(video_path),
            input_srt_path=srt_path_str
        )

        # Create a new processing task record
        from ...models.task import TaskType
        task_result = processing_service._create_processing_task(
            project_id=project_id,
            task_type=TaskType.VIDEO_PROCESSING
        )

        # Update the task's Celery task ID
        task_result.celery_task_id = celery_task.id
        processing_service.db.commit()

        return {
            "message": "Processing retry started successfully",
            "project_id": project_id,
            "task_id": task_result.id,
            "celery_task_id": celery_task.id,
            "status": "processing"
        }

    except HTTPException:
        raise
    except Exception as e:
        # Error notification - WebSocket notifications disabled
        # try:
        #     await websocket_service.send_processing_error(
        #         project_id=int(project_id),
        #         error=str(e),
        #         step="retry_initialization"
        #     )
        # except:
        #     pass
        logger.exception("Failed to retry project processing: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to retry processing; please try again later")


@router.post("/{project_id}/resume")
async def resume_processing(
    project_id: str,
    start_step: str = Form(..., description="Step to resume from (step1_outline, step2_timeline, etc.)"),
    project_service: ProjectService = Depends(get_project_service),
    processing_service: ProcessingService = Depends(get_processing_service)
):
    """Resume processing from a specific step."""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Check the project status
        if project.status.value not in ["failed", "processing", "pending"]:
            raise HTTPException(status_code=400, detail="Project is not in failed, processing, or pending status")

        # Resolve the SRT path (when needed)
        srt_path = None
        if start_step == "step1_outline":
            if project.processing_config and "srt_file" in project.processing_config:
                from pathlib import Path
                project_root = Path(__file__).parent.parent.parent / "data" / "projects" / project_id
                srt_path = project_root / "raw" / project.processing_config["srt_file"]

            if not srt_path or not srt_path.exists():
                raise HTTPException(status_code=400, detail=f"SRT file not found: {srt_path}")

        # Resume via the processing service
        result = processing_service.resume_processing(project_id, start_step, srt_path)

        return {
            "message": f"Processing resumed from {start_step} successfully",
            "project_id": project_id,
            "start_step": start_step,
            "result": result
        }
    except Exception as e:
        logger.exception("Failed to resume project processing: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to resume processing; please try again later")


@router.get("/{project_id}/status")
async def get_processing_status(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service),
    processing_service: ProcessingService = Depends(get_processing_service)
):
    """Get processing status of a project."""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Get the latest task
        tasks = project.tasks if hasattr(project, 'tasks') else []
        latest_task = None
        if tasks:
            latest_task = max(tasks, key=lambda t: t.created_at) if hasattr(tasks[0], 'created_at') else tasks[0]

        if not latest_task:
            return {
                "status": "pending",
                "current_step": 0,
                "total_steps": 6,
                "step_name": "Waiting to start",
                "progress": 0,
                "error_message": None
            }

        # Get the processing status
        status = processing_service.get_processing_status(project_id, str(latest_task.id))

        return status
    except Exception as e:
        logger.exception("Failed to get processing status: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to get processing status; please try again later")


@router.get("/{project_id}/logs")
async def get_project_logs(
    project_id: str,
    lines: int = Query(50, ge=1, le=1000, description="Number of log lines to return"),
    project_service: ProjectService = Depends(get_project_service)
):
    """Get project logs."""
    try:
        # Mock log data; real implementation should query the log service
        return {
            "logs": [
                {
                    "timestamp": "2025-08-01T13:30:00.000Z",
                    "module": "processing",
                    "level": "INFO",
                    "message": "Started processing project"
                },
                {
                    "timestamp": "2025-08-01T13:30:05.000Z",
                    "module": "processing",
                    "level": "INFO",
                    "message": "Step 1: outline extraction done"
                },
                {
                    "timestamp": "2025-08-01T13:30:10.000Z",
                    "module": "processing",
                    "level": "INFO",
                    "message": "Step 2: timeline location done"
                },
                {
                    "timestamp": "2025-08-01T13:30:15.000Z",
                    "module": "processing",
                    "level": "INFO",
                    "message": "Step 3: content scoring in progress..."
                }
            ]
        }
    except Exception as e:
        logger.exception("Failed to get project logs: %s", project_id)
        raise HTTPException(status_code=500, detail="Failed to get project logs; please try again later")


@router.get("/{project_id}/import-status")
async def get_import_status(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service)
):
    """Get project import status"""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Check for running import tasks
        from backend.celery_app import celery_app

        # More elaborate task-state checks could go here
        # For now simply return the project status
        return {
            "project_id": project_id,
            "status": project.status.value,
            "message": "Import status OK"
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get import status: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to get import status: {str(e)}")


@router.post("/{project_id}/generate-thumbnail")
async def generate_project_thumbnail(
    project_id: str,
    project_service: ProjectService = Depends(get_project_service)
):
    """Generate a thumbnail for a project"""
    try:
        # Fetch the project
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Check for a video file
        if not project.video_path:
            raise HTTPException(status_code=400, detail="Project has no video file")

        # Check the video file exists
        video_path = Path(project.video_path)
        if not video_path.exists():
            raise HTTPException(status_code=400, detail="Video file not found")

        # Generate the thumbnail
        from ...utils.thumbnail_generator import generate_project_thumbnail
        thumbnail_data = generate_project_thumbnail(project_id, video_path)

        if thumbnail_data:
            # Save the thumbnail to the database
            project.thumbnail = thumbnail_data
            project_service.db.commit()

            return {
                "success": True,
                "thumbnail": thumbnail_data,
                "message": "Thumbnail generated and saved"
            }
        else:
            raise HTTPException(status_code=500, detail="Thumbnail generation failed")

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to generate project thumbnail: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate thumbnail: {str(e)}")


@router.get("/{project_id}/files/{filename}")
async def get_project_file(
    project_id: str,
    filename: str,
    project_service: ProjectService = Depends(get_project_service)
):
    """Get a project file by filename."""
    try:
        from pathlib import Path
        import json
        from fastapi.responses import FileResponse

        # Build the file path - using the correct project directory
        from ...core.path_utils import get_project_directory
        project_root = get_project_directory(project_id)

        # Try multiple candidate paths
        possible_paths = [
            project_root / "raw" / filename,  # raw files
            project_root / "metadata" / filename,  # metadata files
            project_root / filename,  # directly under the project root
        ]

        file_path = None
        for path in possible_paths:
            if path.exists():
                file_path = path
                break

        if not file_path:
            raise HTTPException(status_code=404, detail="File not found")

        # Return different responses by file type
        if filename.endswith('.json'):
            # Return JSON data
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            return data
        else:
            # Other files (e.g. video) return a stream
            media_type = "video/mp4" if filename.endswith('.mp4') else "application/octet-stream"
            return FileResponse(
                path=str(file_path),
                filename=filename,
                media_type=media_type,
                headers={
                    "Accept-Ranges": "bytes",  # range requests for video playback
                    "Cache-Control": "public, max-age=3600"  # cache for 1 hour
                }
            )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to get project file: %s/%s", project_id, filename)
        raise HTTPException(status_code=500, detail="Failed to get project file; please try again later")


@router.get("/{project_id}/clips/{clip_id}")
async def get_project_clip(
    project_id: str,
    clip_id: str,
    project_service: ProjectService = Depends(get_project_service)
):
    """Get a specific clip video file for a project."""
    try:
        from pathlib import Path
        import os

        # Build the video path - using the correct project directory
        from ...core.path_utils import get_project_directory
        project_dir = get_project_directory(project_id)
        clips_dir = project_dir / "output" / "clips"

        # Ensure the path exists
        if not clips_dir.exists():
            raise HTTPException(status_code=404, detail=f"Clips directory not found: {clips_dir}")

        # Find the matching video file
        # First try clip_id directly
        video_files = list(clips_dir.glob(f"{clip_id}_*.mp4"))

        # Fall back to matching via the database
        if not video_files:
            from ...models.clip import Clip
            clip = project_service.db.query(Clip).filter(Clip.id == clip_id).first()
            if clip and clip.video_path:
                video_file_path = Path(clip.video_path)
                if video_file_path.exists():
                    video_file = video_file_path
                else:
                    raise HTTPException(status_code=404, detail=f"Clip video file not found for clip_id: {clip_id}")
            else:
                raise HTTPException(status_code=404, detail=f"Clip not found in database: {clip_id}")
        else:
            video_file = video_files[0]

        # Check the file exists
        if not video_file.exists():
            raise HTTPException(status_code=404, detail="Clip video file not found")

        # Return the file stream
        from fastapi.responses import FileResponse
        return FileResponse(
            path=str(video_file),
            media_type="video/mp4",
            filename=video_file.name
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Failed to get project clip: %s/%s", project_id, clip_id)
        raise HTTPException(status_code=500, detail="Failed to get clip file; please try again later")


@router.post("/sync-all")
async def sync_all_projects_from_filesystem(
    db: Session = Depends(get_db)
):
    """Sync all projects from the filesystem to the database"""
    try:
        from backend.services.data_sync_service import DataSyncService
        from backend.core.config import get_data_directory

        # Get the data directory
        data_dir = get_data_directory()

        # Create the sync service
        sync_service = DataSyncService(db)

        # Sync all projects
        result = sync_service.sync_all_projects_from_filesystem(data_dir)

        return {
            "success": result.get("success", False),
            "message": "Data sync completed",
            "synced_projects": result.get("synced_projects", []),
            "failed_projects": result.get("failed_projects", []),
            "total_synced": len(result.get("synced_projects", [])),
            "total_failed": len(result.get("failed_projects", []))
        }

    except Exception as e:
        logger.error(f"Failed to sync all projects: {e}")
        raise HTTPException(status_code=500, detail=f"Sync failed: {str(e)}")


@router.patch("/{project_id}/collections/{collection_id}/reorder")
async def reorder_collection_clips(
    project_id: str,
    collection_id: str,
    clip_ids: List[str],
    db: Session = Depends(get_db)
):
    """Reorder clips in a collection"""
    try:
        from backend.services.collection_service import CollectionService

        # Create the collection service
        collection_service = CollectionService(db)

        # Fetch the collection
        collection = collection_service.get(collection_id)
        if not collection:
            raise HTTPException(status_code=404, detail="Collection not found")

        # Verify the collection belongs to this project
        if str(collection.project_id) != project_id:
            raise HTTPException(status_code=400, detail="Collection does not belong to the specified project")

        # Update clip_ids in collection_metadata
        metadata = getattr(collection, 'collection_metadata', {}) or {}
        metadata['clip_ids'] = clip_ids

        # Update the collection_metadata column directly
        from sqlalchemy import update
        from backend.models.collection import Collection

        stmt = update(Collection).where(Collection.id == collection_id).values(
            collection_metadata=metadata
        )
        collection_service.db.execute(stmt)
        collection_service.db.commit()

        return {
            "message": "Collection clips reordered successfully",
            "clip_ids": clip_ids
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to reorder clips in collection {collection_id}: {e}")
        raise HTTPException(status_code=500, detail=f"Reorder failed: {str(e)}")


@router.post("/sync/{project_id}")
async def sync_project_from_filesystem(
    project_id: str,
    db: Session = Depends(get_db)
):
    """Sync one project from the filesystem to the database"""
    try:
        from backend.services.data_sync_service import DataSyncService
        from backend.core.config import get_data_directory

        # Get the data directory
        data_dir = get_data_directory()
        project_dir = data_dir / "projects" / project_id

        if not project_dir.exists():
            raise HTTPException(status_code=404, detail=f"Project directory not found: {project_id}")

        # Create the sync service
        sync_service = DataSyncService(db)

        # Sync the project
        result = sync_service.sync_project_from_filesystem(project_id, project_dir)

        return {
            "success": result.get("success", False),
            "project_id": project_id,
            "clips_synced": result.get("clips_synced", 0),
            "collections_synced": result.get("collections_synced", 0),
            "message": f"Project {project_id} synced"
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to sync project {project_id}: {e}")
        raise HTTPException(status_code=500, detail=f"Sync failed: {str(e)}")


@router.post("/{project_id}/collections/{collection_id}/generate")
async def generate_collection_video(
    project_id: str,
    collection_id: str,
    db: Session = Depends(get_db),
    project_service: ProjectService = Depends(get_project_service)
):
    """Generate a collection video"""
    try:
        from ...models.collection import Collection
        from ...models.clip import Clip
        from ...utils.video_processor import VideoProcessor
        from ...core.path_utils import get_project_directory
        from pathlib import Path
        import json

        # Verify the project exists
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Fetch the collection record
        collection = db.query(Collection).filter(Collection.id == collection_id).first()
        if not collection:
            raise HTTPException(status_code=404, detail="Collection not found")

        # Verify the collection belongs to this project
        if str(collection.project_id) != project_id:
            raise HTTPException(status_code=400, detail="Collection does not belong to the specified project")

        # Get the clip ID list
        metadata = getattr(collection, 'collection_metadata', {}) or {}
        clip_ids = metadata.get('clip_ids', [])

        if not clip_ids:
            raise HTTPException(status_code=400, detail="Collection contains no clips")

        # Fetch clips in the user-defined order
        clips_dict = {clip.id: clip for clip in db.query(Clip).filter(Clip.id.in_(clip_ids)).all()}
        if len(clips_dict) != len(clip_ids):
            raise HTTPException(status_code=400, detail="Some clips not found")

        # Order clips as the user arranged them
        ordered_clips = [clips_dict[clip_id] for clip_id in clip_ids if clip_id in clips_dict]

        # Get the project directory
        project_dir = get_project_directory(project_id)
        collections_dir = project_dir / "output" / "collections"
        collections_dir.mkdir(parents=True, exist_ok=True)

        # Collect clip video paths in order
        clips_dir = project_dir / "output" / "clips"
        clip_video_paths = []

        for clip in ordered_clips:
            if clip.video_path and Path(clip.video_path).exists():
                clip_video_paths.append(Path(clip.video_path))
            else:
                # Look inside the clips directory
                possible_paths = [
                    clips_dir / f"{clip.id}_*.mp4",
                    clips_dir / f"clip_{clip.id}.mp4",
                    clips_dir / f"{clip.id}.mp4"
                ]

                found = False
                for pattern in possible_paths:
                    if pattern.name.endswith('*'):
                        # Handle globs
                        matches = list(clips_dir.glob(pattern.name))
                        if matches:
                            clip_video_paths.append(matches[0])
                            found = True
                            break
                    else:
                        if pattern.exists():
                            clip_video_paths.append(pattern)
                            found = True
                            break

                if not found:
                    raise HTTPException(status_code=404, detail=f"Clip video file not found: {clip.id}")

        # Name the collection video after the collection title
        collection_name = collection.name or f"collection_{collection_id}"
        # Sanitize the filename via VideoProcessor
        from ...utils.video_processor import VideoProcessor
        safe_name = VideoProcessor.sanitize_filename(collection_name)
        output_filename = f"{safe_name}.mp4"
        output_path = collections_dir / output_filename

        # Build the collection with VideoProcessor
        video_processor = VideoProcessor(
            clips_dir=str(clips_dir),
            collections_dir=str(collections_dir)
        )
        success = video_processor.create_collection(clip_video_paths, output_path)

        if not success:
            raise HTTPException(status_code=500, detail="Failed to generate collection video")

        # Generate the collection cover
        thumbnail_path = None
        try:
            thumbnail_filename = f"{collection_id}_{safe_name}_thumbnail.jpg"
            thumbnail_path = collections_dir / thumbnail_filename

            # Extract the cover from the video (frame at 5s)
            thumbnail_success = video_processor.extract_thumbnail(output_path, thumbnail_path, time_offset=5)
            if thumbnail_success:
                collection.thumbnail_path = str(thumbnail_path)
                logger.info(f"Collection cover generated: {thumbnail_path}")
            else:
                logger.warning(f"Collection cover generation failed: {collection_id}")
        except Exception as e:
            logger.error(f"Error generating collection cover: {e}")

        # Update the collection's export_path
        collection.export_path = str(output_path)
        db.commit()

        return {
            "success": True,
            "message": "Collection video generated",
            "collection_id": collection_id,
            "output_path": str(output_path),
            "filename": output_filename
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to generate collection video: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate collection video: {str(e)}")


@router.get("/{project_id}/download")
async def download_project_file(
    project_id: str,
    clip_id: Optional[str] = Query(None, description="Download a specific clip"),
    collection_id: Optional[str] = Query(None, description="Download a specific collection"),
    db: Session = Depends(get_db),
    project_service: ProjectService = Depends(get_project_service)
):
    """Download a project file (clip or collection)"""
    try:
        from fastapi.responses import FileResponse
        from pathlib import Path

        # Verify the project exists
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        if collection_id:
            # Download the collection video
            from ...models.collection import Collection
            collection = db.query(Collection).filter(Collection.id == collection_id).first()
            if not collection:
                raise HTTPException(status_code=404, detail="Collection not found")

            if not collection.export_path:
                raise HTTPException(status_code=404, detail="Collection video file not found")

            file_path = Path(collection.export_path)
            if not file_path.exists():
                raise HTTPException(status_code=404, detail="Collection video file not found")

            # Build the download filename
            collection_name = collection.name or f"collection_{collection_id}"
            from ...utils.video_processor import VideoProcessor
            safe_name = VideoProcessor.sanitize_filename(collection_name)
            filename = f"{safe_name}.mp4"

            # URL-encode the filename
            import urllib.parse
            encoded_filename = urllib.parse.quote(filename.encode('utf-8'))

            return FileResponse(
                path=str(file_path),
                filename=filename,
                media_type="video/mp4",
                headers={
                    "Content-Disposition": f"attachment; filename*=UTF-8''{encoded_filename}"
                }
            )

        elif clip_id:
            # Download the clip video
            from ...models.clip import Clip
            clip = db.query(Clip).filter(Clip.id == clip_id).first()
            if not clip:
                raise HTTPException(status_code=404, detail="Clip not found")

            if not clip.video_path:
                raise HTTPException(status_code=404, detail="Clip video file not found")

            file_path = Path(clip.video_path)
            if not file_path.exists():
                raise HTTPException(status_code=404, detail="Clip video file not found")

            # Build the download filename
            clip_title = clip.title or f"clip_{clip_id}"
            from ...utils.video_processor import VideoProcessor
            safe_name = VideoProcessor.sanitize_filename(clip_title)
            filename = f"{safe_name}.mp4"

            # URL-encode the filename
            import urllib.parse
            encoded_filename = urllib.parse.quote(filename.encode('utf-8'))

            return FileResponse(
                path=str(file_path),
                filename=filename,
                media_type="video/mp4",
                headers={
                    "Content-Disposition": f"attachment; filename*=UTF-8''{encoded_filename}"
                }
            )

        else:
            raise HTTPException(status_code=400, detail="clip_id or collection_id is required")

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to download file: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to download file: {str(e)}")


@router.get("/{project_id}/collections/{collection_id}/thumbnail")
async def get_collection_thumbnail(
    project_id: str,
    collection_id: str,
    db: Session = Depends(get_db),
    project_service: ProjectService = Depends(get_project_service)
):
    """Get a collection cover image"""
    try:
        from fastapi.responses import FileResponse
        from pathlib import Path

        # Verify the project exists
        project = project_service.get(project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")

        # Fetch the collection record
        from ...models.collection import Collection
        collection = db.query(Collection).filter(Collection.id == collection_id).first()
        if not collection:
            raise HTTPException(status_code=404, detail="Collection not found")

        # Verify the collection belongs to this project
        if str(collection.project_id) != project_id:
            raise HTTPException(status_code=400, detail="Collection does not belong to the specified project")

        # Check for a cover
        if not collection.thumbnail_path:
            raise HTTPException(status_code=404, detail="Collection cover not found")

        thumbnail_path = Path(collection.thumbnail_path)
        if not thumbnail_path.exists():
            raise HTTPException(status_code=404, detail="Collection cover file not found")

        return FileResponse(
            path=str(thumbnail_path),
            media_type="image/jpeg",
            headers={
                "Cache-Control": "public, max-age=3600"  # cache for 1 hour
            }
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to get collection cover: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to get collection cover: {str(e)}")


# ---------------------------------------------------------------- Publish export ---
from pydantic import BaseModel, Field


class ClipExportRequest(BaseModel):
    preset: str = Field("douyin", description="douyin / xiaohongshu / shorts / bilibili / original")
    subtitles: bool = True
    title_card: bool = True
    layout: Optional[str] = Field(None, description="Override preset framing: blur / crop / fit / none")


@router.get("/{project_id}/export-presets")
async def list_export_presets(project_id: str):
    from backend.services.publish_export import list_presets
    return {"presets": list_presets()}


@router.post("/{project_id}/clips/{clip_id}/export")
async def start_clip_export(project_id: str, clip_id: str, body: ClipExportRequest = ClipExportRequest()):
    from backend.services.publish_export import ExportRequest, start_export, load_clip_meta
    try:
        load_clip_meta(project_id, clip_id)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    return start_export(ExportRequest(
        project_id=project_id, clip_id=clip_id, preset=body.preset,
        subtitles=body.subtitles, title_card=body.title_card, layout=body.layout,
    ))


@router.get("/{project_id}/exports/{job_id}")
async def get_clip_export_job(project_id: str, job_id: str):
    from backend.services.publish_export import get_export_job
    job = get_export_job(job_id)
    if not job or job.get("project_id") != project_id:
        raise HTTPException(status_code=404, detail="Export job not found")
    return job


@router.get("/{project_id}/exports/{job_id}/download")
async def download_clip_export(project_id: str, job_id: str):
    from fastapi.responses import FileResponse
    from backend.services.publish_export import get_export_job
    job = get_export_job(job_id)
    if not job or job.get("project_id") != project_id:
        raise HTTPException(status_code=404, detail="Export job not found")
    if job.get("status") != "completed" or not (job.get("result") or {}).get("path"):
        raise HTTPException(status_code=409, detail="Export not finished yet")
    path = Path(job["result"]["path"])
    if not path.exists():
        raise HTTPException(status_code=404, detail="Export file not found")
    return FileResponse(path=str(path), media_type="video/mp4", filename=path.name)